package frontend; // [cite: 351]

import backend.*; // [cite: 377]
import java.util.ArrayList; // [cite: 378]
import javax.swing.table.DefaultTableModel; // [cite: 379]

public class FrmKategori extends javax.swing.JFrame {
   /**
     * Creates new form FrmKategori
     */
    public FrmKategori() {
        initComponents(); // [cite: 422]
        tampilkanData(); // [cite: 423]
        kosongkanForm(); // [cite: 423]
    }

    public void kosongkanForm() {
        txtIdKategori.setText("0"); // [cite: 382]
        txtNama.setText(""); // [cite: 383]
        txtKeterangan.setText(""); // [cite: 384]
    }

    public void tampilkanData() {
        String[] kolom = {"ID", "Nama", "Keterangan"}; // [cite: 392]
        ArrayList<Kategori> list = new Kategori().getAll(); // [cite: 392]
        Object rowData[] = new Object[3]; // [cite: 392]

        tblKategori.setModel(new DefaultTableModel(new Object[][]{}, kolom)); // [cite: 394]

        for (Kategori kat : list) { // [cite: 395]
            rowData[0] = kat.getIdkategori(); // [cite: 396]
            rowData[1] = kat.getNama(); // [cite: 397]
            rowData[2] = kat.getKeterangan(); // [cite: 398]
            ((DefaultTableModel) tblKategori.getModel()).addRow(rowData); // [cite: 399]
        }
    }

    public void cari(String keyword) {
        String[] kolom = {"ID", "Nama", "Keterangan"}; // [cite: 409]
        ArrayList<Kategori> list = new Kategori().search(keyword); // [cite: 409]
        Object rowData[] = new Object[3]; // [cite: 410]

        tblKategori.setModel(new DefaultTableModel(new Object[][]{}, kolom)); // [cite: 411]

        for (Kategori kat : list) { // [cite: 412]
            rowData[0] = kat.getIdkategori(); // [cite: 413]
            rowData[1] = kat.getNama(); // [cite: 414]
            rowData[2] = kat.getKeterangan(); // [cite: 415]
            ((DefaultTableModel) tblKategori.getModel()).addRow(rowData); // [cite: 416]
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        // ... Kode ini di-generate oleh NetBeans Designer
        // ... Deklarasi komponen (txtIdKategori, txtNama, etc.) juga ada di sini
    }// </editor-fold>

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) { // [cite: 427]
        Kategori kat = new Kategori(); // [cite: 429]
        kat.setIdkategori(Integer.parseInt(txtIdKategori.getText())); // [cite: 430]
        kat.setNama(txtNama.getText()); // [cite: 431]
        kat.setKeterangan(txtKeterangan.getText()); // [cite: 432]
        kat.save(); // [cite: 433]
        txtIdKategori.setText(Integer.toString(kat.getIdkategori())); // [cite: 434]
        tampilkanData(); // [cite: 435]
    } // [cite: 427]

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) { // [cite: 437]
        DefaultTableModel model = (DefaultTableModel) tblKategori.getModel(); // [cite: 437]
        int row = tblKategori.getSelectedRow(); // [cite: 438, 439]

        Kategori kat = new Kategori().getById(Integer.parseInt(model.getValueAt(row, 0).toString())); // [cite: 440, 443]
        kat.delete(); // [cite: 441]
        kosongkanForm(); // [cite: 442]
        tampilkanData(); // [cite: 444]
    } // [cite: 437]

    private void btnTambahBaruActionPerformed(java.awt.event.ActionEvent evt) { // [cite: 447]
        kosongkanForm(); // [cite: 447]
    } // [cite: 447]

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) { // [cite: 450]
        cari(txtCari.getText()); // [cite: 451]
    } // [cite: 450]

    private void tblKategoriMouseClicked(java.awt.event.MouseEvent evt) { // [cite: 455]
        DefaultTableModel model = (DefaultTableModel) tblKategori.getModel(); // [cite: 457]
        int row = tblKategori.getSelectedRow(); // [cite: 458, 459]

        txtIdKategori.setText(model.getValueAt(row, 0).toString()); // [cite: 461]
        txtNama.setText(model.getValueAt(row, 1).toString()); // [cite: 461]
        txtKeterangan.setText(model.getValueAt(row, 2).toString()); // [cite: 461]
    } // [cite: 455]

    // ... (Main method dan deklarasi variabel - di-generate NetBeans)

    // Deklarasi variabel komponen (dibuat oleh desainer NetBeans) [cite: 374]
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahBaru;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdKategori;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNama;
    // ... (dan komponen lain seperti JLabel, JScrollPane)
}